; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1
monitor_speed = 115200
upload_port = /dev/ttyUSB0
board_build.partitions = mypartitions.csv
lib_deps =
    mathieucarbou/ESP Async WebServer@^3.0.6
    bblanchon/ArduinoJson@7.3.1
    adafruit/Adafruit GFX Library@^1.12.0
    adafruit/Adafruit BusIO@^1.17.0
    adafruit/Adafruit BMP280 Library@^2.6.8
    adafruit/Adafruit AHTX0@^2.0.5
    adafruit/Adafruit Unified Sensor@^1.1.15
    adafruit/Adafruit SGP30 Sensor@^2.0.3
    olikraus/U8g2_for_Adafruit_GFX@^1.8.0
    northernwidget/DS3231@^1.1.2
    mischief/lua@^0.1.1
    ricmoo/QRCode@^0.0.1

[env:2_1inch]
platform = ${common.platform}
framework = ${common.framework}
board = ${common.board}
monitor_speed = ${common.monitor_speed}
upload_port = ${common.upload_port}
build_flags = 
  -D CONFIG_SPI_MOSI=14 
  -D CONFIG_SPI_MISO=-1
  -D CONFIG_SPI_SCK=13 
  -D CONFIG_SPI_CS=12 
  -D CONFIG_PIN_DC=11 
  -D CONFIG_PIN_RST=10 
  -D CONFIG_PIN_BUSY=9
  -D PIN_ADC=16
  -D PIN_BUTTONL=5
  -D PIN_BUTTONC=6
  -D PIN_BUTTONR=1
  -D PIN_RTC_IRQ=2
  -D PIN_SDVDD_CTRL=21
  -D PIN_CHARGING=7
  -D PIN_SD_CS=47
  -D PIN_SD_MOSI=46
  -D PIN_SD_SCLK=48
  -D PIN_SD_MISO=45
  -D PIN_SD_CARDDETECT=4
  -D PIN_BUZZER=17
  -D PIN_SDA=8
  -D PIN_SCL=15
board_build.partitions = ${common.board_build.partitions}
lib_deps = ${common.lib_deps}

[env:2_9inchV03]
platform = ${common.platform}
framework = ${common.framework}
board = ${common.board}
monitor_speed = ${common.monitor_speed}
upload_port = ${common.upload_port}
build_flags = 
  -D CONFIG_SPI_MOSI=11 
  -D CONFIG_SPI_MISO=-1
  -D CONFIG_SPI_SCK=12 
  -D CONFIG_SPI_CS=10 
  -D CONFIG_PIN_DC=13 
  -D CONFIG_PIN_RST=14 
  -D CONFIG_PIN_BUSY=15
  -D PIN_ADC=16
  -D PIN_BUTTONL=5
  -D PIN_BUTTONC=6
  -D PIN_BUTTONR=1
  -D PIN_RTC_IRQ=2
  -D PIN_SDVDD_CTRL=21
  -D PIN_CHARGING=7
  -D PIN_SD_CS=47
  -D PIN_SD_MOSI=46
  -D PIN_SD_SCLK=48
  -D PIN_SD_MISO=45
  -D PIN_SD_CARDDETECT=4
  -D PIN_BUZZER=17
  -D PIN_SDA=8
  -D PIN_SCL=15
board_build.partitions = ${common.board_build.partitions}
lib_deps = ${common.lib_deps}